# Generated by Django 2.1.2 on 2019-03-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kepan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=10, unique=True, verbose_name='订单号')),
                ('name_man', models.CharField(blank=True, max_length=50, null=True, verbose_name='先生姓名')),
                ('name_wom', models.CharField(blank=True, max_length=50, null=True, verbose_name='小姐姓名')),
                ('status', models.PositiveIntegerField(choices=[(0, '未完成'), (1, '已完成')], default=0, verbose_name='刻盘状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '刻盘记录',
                'verbose_name_plural': '刻盘记录',
            },
        ),
    ]
