# Generated by Django 2.1.2 on 2019-03-22 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kepan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kepan',
            options={'ordering': ['-order'], 'verbose_name': '刻盘记录', 'verbose_name_plural': '刻盘记录'},
        ),
        migrations.AlterField(
            model_name='kepan',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
