# Generated by Django 2.1.2 on 2019-03-22 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepan', '0002_auto_20190322_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kepan',
            name='created_time',
            field=models.DateField(default=datetime.date.today, verbose_name='创建时间'),
        ),
    ]
