# Generated by Django 2.1.2 on 2019-03-22 08:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shejishi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='设计师名字')),
            ],
            options={
                'verbose_name': '设计师',
                'verbose_name_plural': '设计师',
            },
        ),
        migrations.CreateModel(
            name='Yeji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('name', models.CharField(max_length=50, verbose_name='客人姓名')),
                ('jiaogao', models.DateField(default=datetime.date(2019, 4, 21), verbose_name='校稿日期')),
                ('taoxi', models.IntegerField(verbose_name='套系金额')),
                ('jiaxuan', models.IntegerField(blank=True, null=True, verbose_name='加选金额')),
                ('chujian_date', models.DateField(blank=True, default='', null=True, verbose_name='出件时间')),
                ('zhangshu', models.IntegerField(blank=True, null=True, verbose_name='照片张数')),
                ('note', models.CharField(max_length=500, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='登记时间')),
                ('jiaogao_own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shejishi_jgown', to='yeji.Shejishi', verbose_name='校稿设计师')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shejishi_own', to='yeji.Shejishi', verbose_name='所属设计师')),
            ],
            options={
                'verbose_name': '业绩登记表',
                'verbose_name_plural': '业绩登记表',
                'ordering': ['-order'],
            },
        ),
    ]
