# Generated by Django 2.1.2 on 2019-03-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeji',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
    ]
