# Generated by Django 2.1.7 on 2019-03-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yeji', '0002_auto_20190322_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shejishi',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='设计师名字'),
        ),
        migrations.AlterField(
            model_name='yeji',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shejishi_own', to='yeji.Shejishi', verbose_name='所属设计师'),
        ),
    ]
